import { useState, type FormEvent } from "react";
import type { GraphType, ProjectDocument, ProjectFolder } from "../../domain/model";
import type { TrashContents } from "../../storage/trashRepository";

type VisibleGraphType = Exclude<GraphType, "journey">;

interface Props {
  projects: ProjectDocument[]; folders: ProjectFolder[]; loading: boolean; error?: string;
  onCreate: (name: string, folderId: string, graphType: GraphType) => Promise<void>;
  onCreateFolder: (name: string) => Promise<void>; onRenameFolder: (folder: ProjectFolder, name: string) => Promise<void>; onDeleteFolder: (folder: ProjectFolder) => Promise<void>;
  onOpen: (project: ProjectDocument) => void; onRename: (project: ProjectDocument, name: string) => Promise<void>; onDelete: (project: ProjectDocument) => Promise<void>; onMove: (project: ProjectDocument, folderId: string) => Promise<void>;
  onImport: (file: File) => Promise<void>; onCreateBenchmark: () => Promise<void>;
  trash: TrashContents; onRestoreProject: (project: ProjectDocument) => Promise<void>; onRestoreFolder: (folder: ProjectFolder) => Promise<void>; onPurgeProject: (project: ProjectDocument) => Promise<void>; onPurgeFolder: (folder: ProjectFolder) => Promise<void>;
  onPreviewTrash: (project: ProjectDocument) => void;
}

export function ProjectHome({ projects, folders, loading, error, onCreate, onCreateFolder, onRenameFolder, onDeleteFolder, onOpen, onRename, onDelete, onMove, onImport, onCreateBenchmark, trash, onRestoreProject, onRestoreFolder, onPurgeProject, onPurgeFolder, onPreviewTrash }: Props) {
  const [creating, setCreating] = useState(false); const [creatingFolder, setCreatingFolder] = useState(false); const [name, setName] = useState(""); const [folderName, setFolderName] = useState(""); const [folderId, setFolderId] = useState(""); const [graphType, setGraphType] = useState<VisibleGraphType>("people"); const [busy, setBusy] = useState(false); const [localError, setLocalError] = useState("");
  const [trashOpen, setTrashOpen] = useState(false);
  const visibleProjects = projects.filter((project) => project.graphType !== "journey");
  const openCreate = (id?: string) => { setFolderId(id ?? folders[0]?.id ?? ""); setCreating(true); };
  const submitCreate = async (event: FormEvent) => { event.preventDefault(); const destination = folderId || folders[0]?.id; if (!name.trim() || !destination) return; setBusy(true); try { await onCreate(name.trim(), destination, graphType); setName(""); setCreating(false); } finally { setBusy(false); } };
  return <main className="project-home"><header className="home-header"><a className="home-brand" href="#top" aria-label="人物关系图谱首页"><span className="home-brand__icon" aria-hidden="true"><i /><i /><i /></span><span>人物关系图谱</span></a><div className="home-header__actions"><button className="button button--ghost" type="button" onClick={() => void onCreateBenchmark()}>创建性能基准项目</button><label className="button button--ghost" htmlFor="project-import">导入项目</label><input id="project-import" className="sr-only" type="file" accept="application/json,.json" aria-label="选择要导入的项目文件" onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ""; if (file) void onImport(file).catch((reason: unknown) => setLocalError(reason instanceof Error ? reason.message : "导入失败")); }} /><button className="button button--ghost" type="button" onClick={() => setTrashOpen(true)}>回收站（{trash.projects.length + trash.folders.length}）</button><button className="button button--primary" type="button" onClick={() => setCreatingFolder(true)}>＋ 新建文件夹</button></div></header>
  <section className="home-hero" id="top"><div><p className="eyebrow">YOUR CHARACTER ATLAS</p><h1>从一部作品开始</h1><p>在一个文件夹中整理人物关系图与地理图。</p></div><div className="hero-orbit" aria-hidden="true"><span /><span /><span /><span /><span /></div></section>
  <section className="project-section" aria-labelledby="project-list-title"><div className="section-heading"><div><p className="section-kicker">本地文件夹</p><h2 id="project-list-title">我的图谱资料</h2></div><span>{folders.length} 个文件夹 · {visibleProjects.length} 张图</span></div>{(error || localError) && <p className="notice notice--error" role="alert">{localError || error}</p>}{loading ? <p className="notice">正在读取本地项目…</p> : folders.length === 0 ? <div className="empty-projects"><div className="empty-projects__symbol">▰</div><h3>还没有图谱文件夹</h3><p>创建文件夹后，可以在其中建立多张关系图。</p><button className="button button--primary" type="button" onClick={() => setCreatingFolder(true)}>新建文件夹</button></div> : <div className="folder-list">{folders.map((folder) => <section className="folder-card" key={folder.id}><header><div><span>▰</span><h3>{folder.name}</h3><small>{visibleProjects.filter((item) => item.folderId === folder.id).length} 张图</small></div><div><button type="button" onClick={() => { const next = window.prompt("文件夹名称", folder.name)?.trim(); if (next) void onRenameFolder(folder, next); }}>重命名</button><button className="danger-link" type="button" onClick={() => void onDeleteFolder(folder)}>删除</button></div></header><div className="project-grid">{visibleProjects.filter((item) => item.folderId === folder.id).map((project, index) => <article className="project-card" key={project.id}><button className="project-card__open" type="button" onClick={() => onOpen(project)}><span className={`project-card__cover project-card__cover--${index % 4 + 1}`}><i /><i /><i /></span><span className="project-card__content"><strong>{project.name}</strong><span>{typeLabel(project.graphType)} · {project.people.length} 个人物 · {project.relationships.length} 条关系</span><small>最近编辑 {formatDate(project.updatedAt)}</small></span></button><div className="project-card__actions"><button type="button" onClick={() => { const next = window.prompt("图谱名称", project.name)?.trim(); if (next) void onRename(project, next); }}>重命名</button><select aria-label={`移动${project.name}到文件夹`} value={project.folderId} onChange={(event) => void onMove(project, event.target.value)}>{folders.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="danger-link" type="button" onClick={() => void onDelete(project)}>删除</button></div></article>)}</div><button className="folder-card__add" type="button" onClick={() => openCreate(folder.id)}>＋ 在此文件夹新建图谱</button></section>)}</div>}</section>
  {creatingFolder && <Dialog title="新建文件夹" onClose={() => setCreatingFolder(false)}><form onSubmit={(event) => { event.preventDefault(); if (!folderName.trim()) return; setBusy(true); void onCreateFolder(folderName.trim()).then(() => { setFolderName(""); setCreatingFolder(false); }).finally(() => setBusy(false)); }}><label htmlFor="folder-name">文件夹名称</label><input id="folder-name" autoFocus value={folderName} onChange={(event) => setFolderName(event.target.value)} /><button className="button button--primary" type="submit" disabled={busy || !folderName.trim()}>创建文件夹</button></form></Dialog>}
  {creating && <Dialog title="新建图谱" onClose={() => setCreating(false)}><form onSubmit={(event) => void submitCreate(event)}><label htmlFor="project-name">图谱名称</label><input id="project-name" autoFocus value={name} onChange={(event) => setName(event.target.value)} /><label htmlFor="project-folder">所属文件夹</label><select id="project-folder" value={folderId} onChange={(event) => setFolderId(event.target.value)}>{folders.map((folder) => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select><label htmlFor="graph-type">图谱类型</label><select id="graph-type" value={graphType} onChange={(event) => setGraphType(event.target.value as VisibleGraphType)}><option value="people">人物关系图</option><option value="geography">地理位置图</option></select><button className="button button--primary" type="submit" disabled={busy || !name.trim() || !folderId}>创建并打开</button></form></Dialog>}{trashOpen && <Dialog title="回收站" onClose={() => setTrashOpen(false)}><p>内容仅保存在当前设备，7 天后自动永久清理。</p><div className="trash-list">{trash.projects.map((item) => <article key={item.id}><strong>{item.name}（剩余 {remainingDays(item.purgeAt)} 天）</strong><button type="button" onClick={() => onPreviewTrash(item)}>预览</button><button type="button" onClick={() => void onRestoreProject(item)}>恢复</button><button type="button" onClick={() => void onPurgeProject(item)}>永久删除</button></article>)}{trash.folders.map((item) => <article key={item.id}><strong>{item.name}（剩余 {remainingDays(item.purgeAt)} 天）</strong><button type="button" onClick={() => void onRestoreFolder(item)}>恢复</button><button type="button" onClick={() => void onPurgeFolder(item)}>永久删除</button></article>)}{!trash.projects.length && !trash.folders.length && <p>回收站为空</p>}</div></Dialog>}</main>;
}

function Dialog({ title, onClose, children }: { title: string; onClose: () => void; children: import("react").ReactNode }) { return <div className="dialog-backdrop" role="presentation"><section className="create-dialog" role="dialog" aria-modal="true" aria-label={title}><button className="dialog-close" type="button" aria-label="关闭" onClick={onClose}>×</button><h2>{title}</h2>{children}</section></div>; }
function typeLabel(type?: GraphType) { return type === "geography" ? "地理位置图" : "人物关系图"; }
function formatDate(value: string) { return new Intl.DateTimeFormat("zh-CN", { month: "short", day: "numeric" }).format(new Date(value)); }
function remainingDays(value?: string) { return value ? Math.max(0, Math.ceil((new Date(value).getTime() - Date.now()) / 86400000)) : 0; }
